version: "3.8"

services:
  mysqldb2:
    image: mysql:8
    container_name: database2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: new
  
    ports:
      - 3306:3306